Changed Startx behavior

diff --git a/mainDotFiles/bash_profile b/mainDotFiles/bash_profile
--- a/mainDotFiles/bash_profile
+++ b/mainDotFiles/bash_profile
@@ -2,7 +2,10 @@
 # ~/.bash_profile
 #Start dwm
 if [ -z "$DISPLAY" ] && [ "$(tty)" = "/dev/tty1" ]; then 
-	exec startx
+	if ! startx; then 
+		echo "Failed to start startx"
+		read -p "Press enter to continue"
+	fi
 fi
 
 [[ -f ~/.bashrc ]] && . ~/.bashrc
